config/routes.rb
Rails.application.routes.draw do
  resources :tool_calls
  resources :messages
  resources :chats
  resource :session
  resources :passwords, param: :token
  get "/home", to: "pages#home"
  get "/about", to: "pages#about"
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake">
  <head>
    <title><%= content_for(:title) || "Ltbot" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# adding fontawesome %>
    <script src="https://kit.fontawesome.com/c756d2fee6.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%# create the navbar %>
   <nav>
     <div class="navbar bg-base-100 shadow-sm">
       <%= link_to "/home", class: "flex-1" do %>
       <i class="fa-solid fa-user-robot fa-2xl fa-shake" style="color: #74C0FC;"></i>
       <span class="btn btn-ghost text-xl">LTBot</span>
     <% end %>
     <div class="flex-none">
       <ul class="menu menu-horizontal px-1">
         <li><%= link_to "About", "/about" %></li>
         <%= tag.li link_to "Login", new_session_path unless authenticated? %>
         <%= tag.li button_to "Log out", session_path, method: :delete if authenticated? %>
         <%# A<li><%= authenticated? == true ? link_to("Log out", home_path, method: :delete) : link_to("Log in", new_session_path) </li> %>
       </ul>
     </div>
   </nav> 

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>

    <footer class="text-center py-4 text-xl">
      Made with <i class="fa-solid fa-heart text-red-500"></i> by <%= link_to "MRL IT", "https://mrlit.merck.com", class: "text-blue-600 hover:text-blue-800 underline" %>
    </footer>
  </body>
</html>